### ISSUE TITLE
Binding Path not set properly for nested complex objects

### ISSUE THREAD

**Issue by NoleHealth** [Oceanware/XAMLPowerToys2015#10]
### Installed product versions
- Visual Studio: 2017 Enterprise
- This extension: I don't see version information in the extension. Latest as of 11/14/2017
### Description
Binding Path not set properly for nested complex objects

### Steps to recreate
View Model -
     ProfilePageViewModel : ObservableObject
Has Property - 
    Profile - type Profile : ObservableObject

Profile has Properties:
  Address - type Address : ObservableObject
  ShippingAddress - type Address : ObservableObject

Address has properties
   AddressLine1,  AddressLine2, City, State, Zip

Add Profile.Address.Zip to form in XAML Power Tools

### Current behavior
The Text binding is set as Text="{Binding Path=Address.Zip, Mode=TwoWay}"

### Expected behavior
The Text binding should be set to Text="{Binding Path=Profile.Address.Zip, Mode=TwoWay}"
Notice the current behavior is dropping the parent Profile.

I am just doing an Replace text to fix at the moment.  Not a big deal.
Thanks for the great tool!

**Comment by kdawg1406** [comment]
@NoleHealth thank you for reporting this.  I'll get into it over Thanksgiving.

Best,

Karl

**Comment by kdawg1406** [comment]
@NoleHealth just checked in the fix.  I've uploaded the new build to the MarketPlace.  Your version will automatically update within VS, or you can visit this url:  https://marketplace.visualstudio.com/items?itemName=KarlShifflettkdawg.XAMLPowerToysforVisualStudio2015  

You'll want to check for version 1.5.29 dated 11/23/2017.  If it's not there yet, check back in a few minutes to get it.

Much appreciate you writing this up, can't believe I didn't catch this before, thank you!

Happy Thanksgiving,

Karl
