### ISSUE TITLE
Extension crashes immediately on activation

### ISSUE THREAD

**Issue by ghost** [Oceanware/XAMLPowerToys2015#11]
### Installed product versions
- Visual Studio 2017 15.5.2
- This extension: 1.5.30

### Description
Extension crashes Visual Studio on activation.

### Steps to recreate
1. Right click within XAML file and select PowerToys 

### Current behavior
Visual Studio crashes immediately. Extension does not open.

View Model attempting to work with within a .NET Standard 2.0 project.

``
using System;
using PropertyChanged;
using ArnMobile.Models;
using Xamarin.Forms;

namespace ArnMobile.ViewModels
{
    [AddINotifyPropertyChangedInterface]
    public class BookingViewModel : AbstactViewModel, IBookingQuery
    {
        public IDestination Destination { get; set; }
        [DependsOn(nameof(Destination))]
        public string DestinationName { get; set; }
        public string LabelForDestinationEntry => "DESTINATION"; // todo: [refactor:M5.1] localize string
        public string PlaceholderForDestinationEntry => " -enter destination- "; // todo: [refactor:M5.1] localize string
        [DependsOn(nameof(DestinationName))]
        public string DestinationText => DestinationName ?? string.Empty;

        public int LocationId => Destination.LocationId;
        public Currency BookingCurrency { get; set; } = Currency.DefaultCurrency;
        public string LabelForCurrencySelection => "CURRENCY";  // todo: [refactor:M5.1] localize string
        public Locale Locale { get; set; } = Locale.DefaultLocale;
        public string LabelForLocaleSelection => "LOCALE";  // todo: [refactor:M5.1] localize string

        private int theAdultCount = 1;
        public int AdultCount {
            get => theAdultCount;
            set => theAdultCount = Math.Max(value, 1);
        }
        public string LabelForAdultCountEntry => "ADULTS";  // todo: [refactor:M5.1] localize string
        public string HotelName { get; set; }
        public string LabelForHotelNameEntry => "HOTEL NAME";  // todo: [refactor:M5.1] localize string
        public string LabelForCheckInDateEntry => "CHECKIN DATE";  // todo: [refactor:M5.1] localize string
        public DateTime CheckInDate { get; set; } = DateTime.Today;

        public string LabelForCheckOutDateEntry => "CHECKOUT DATE";  // todo: [refactor:M5.1] localize string
        private DateTime theCheckOutDate;
        [DependsOn(nameof(EarliestCheckOutDate))]
        public DateTime CheckOutDate {
            get {
                if (theCheckOutDate == null || theCheckOutDate < EarliestCheckOutDate)
                {
                    theCheckOutDate = EarliestCheckOutDate;
                }
                return EarliestCheckOutDate;
            }
            set => new DateTime(Math.Max(EarliestCheckOutDate.Ticks, value.Ticks));
        }
        /// <summary>
        /// Earliest day for checkout out
        /// </summary>
        /// <remarks>
        /// Minimum 1 day
        /// </remarks>
        [DependsOn(nameof(CheckInDate))]
        public DateTime EarliestCheckOutDate => CheckInDate.AddDays(1);
        private int theChildCount = 0;
        public int ChildCount { get => theChildCount; set => theChildCount = Math.Max(value, 0); }
        [DependsOn(nameof(CheckInDate), nameof(CheckOutDate))]
        public string LabelForChildCountEntry => "CHILDREN";  // todo: [refactor:M5.1] localize string
        public int DaysTolerance => 1;
        public string LabelForDaysToleranceEntry => "TOLERANCE"; // todo: [refactor:M5.1] localize string
        public int Days => (CheckOutDate - CheckInDate).Days;
        public string LabelForDaysDisplayed => "DAYS"; // todo: [refactor:M5.1] localize string
        public int DaysOut => Math.Max((CheckInDate - DateTime.Today).Days, 0);
        private int theRoomCount = 1;
        public int RoomCount { get => theRoomCount; set => theRoomCount = Math.Max(value, 1); }
        public string LabelForRoomCountEntry => "ROOM NEEDED"; // todo: [refactor:M5.1] localize string
        public override string Title { get; set; }

        public override bool IsBusy { get; protected set; }

        public string SortType => "bestvalue"; // todo: [refactor:M5.1] remove option constant from code
        public string SortOrder => "ASC"; // todo: [refactor:M5.1] remove option const from code
        public string SortColumn => ""; // todo: [refactor:M5.1] implement sort column (?)

        public string[] PropertyTypes => new[] { "" }; //todo: [refactor: M5.1] implement selector for property types (under advanced search)
        public string[] PropertyClasses => new[] { "" }; //todo: [refactor: M5.1] implement selector for property classes (under advanced search)
        public string[] PropertyIds => new[] { "" };  //todo: [refactor: M5.1] implement selector for property ids (under advanced search)

        public Command SearchDestinations { get; set; } // todo: implement command 
        public Command SearchAvailableHotels { get; set; } // todo: implement command

    }
}

**Comment by kdawg1406** [comment]
@rafaelubaldo is this view model in your demo you sent me?  If not, please add to demo, verify it's broken, and send me a link to the project.

Best,

Karl

**Comment by rafaelubaldo** [comment]
Hey, @kdawg1406 

Thanks for the quick response. This line causes the failure:

    public Currency BookingCurrency { get; set; } = Currency.DefaultCurrency;

Currency.DefaultCurrency refers to a property that produces an new instance of Currency. Upon changing to a method, everything appears to work. 

I will draft up a complete test case tonight. 

Thanks.

**Comment by kdawg1406** [comment]
@rafaelubaldo OK.  Yea, not sure if this is a Mono Cecil issue or not.  

Glad you found the issue that causes it.  I'm actually surprised XAML Power Toys has not driven me crazy with all the .NET changes and assumptions I made years ago that are still working.  LOL.

Best,

Karl

**Comment by kdawg1406** [comment]
I spent hours trying to upgrade this extension. I've given up. If you want to continue to use this, please make any changes you need to be successful.

**Comment by kdawg1406** [comment]
I've figured out how to update XPT's to VS 2017 and VS 2019

https://marketplace.visualstudio.com/items?itemName=KarlShifflettkdawg.XAMLPowerToysforVisualStudio2015

Install and have fun!

Best to you,

Karl
