### ISSUE TITLE
Not working as described

### ISSUE THREAD

**Issue by BillNoble** [Oceanware/XAMLPowerToys2015#12]
**FIXED !
Not your application causing the issue.
I needed to install a Microsoft extension to enable various files.
Sorry !
And thanks for your work :-)**

### Installed product versions
- Visual Studio: [2017 15.6.2 community]
- This extension: [example 1.5.31]

### Description
Installs but will not showing when r-Clicked. Not showing in tool etc.

### Steps to recreate
1. Download
2. Create Xamarin Forms Project
3. r-Click in code
4. Nothing

### Current behavior
Nothing working

### Expected behavior
Should work as expected

**Comment by kdawg1406** [comment]
Fantastic!!  Have a great day.
