### ISSUE TITLE
PowerToys doesn´t play with  ObservableRangeCollection

### ISSUE THREAD

**Issue by sturlath** [Oceanware/XAMLPowerToys2015#2]
### Installed product versions
- Visual Studio: 2015 Professional
- This extension:  1.2.17

### Description
When using PowerToys on a view model that uses [ObservableRangeCollection  ](https://www.nuget.org/packages/Refractored.MvvmHelpers/)from (James´s Montemagno´s  Refactored.MvvmHelpers) throws the following error 

> Failed to resolve assembly: 'MvvvmHelpers, Version=1.0.1.0, Culture=nutral,PublicKeyToken=null'

I´m frankly not sure if this is an error at all (or you just don´t support his collection) or if its on your or his side. If it´s on his, can he fix anything? I realy would like to use his collection with your tool..

### Steps to recreate
1. Create a Xamarin.Forms project and change it to Netstandard1.4 library with "imports": "portable-monoandroid10+monotouch10+net45+win+win81+wp8+wpa81+xamarinios10" (**could this be a netstandard issue?)**
2. Install [MvvmHelpers]( https://www.nuget.org/packages/Refractored.MvvmHelpers/)
2. Create a Page and ViewModel
3. Add the following line to the viewModel
`publicObservableRangeCollection<SomeClass> StartupCells { get; } = new ObservableRangeCollection<SomeClass>();` 
4. Try using PowerToys on the XAML

### Current behavior
Error window is displayed when I right click the xaml file and choose "XAML Power Toys" 

### Expected behavior
Should display the editor.

**Comment by kdawg1406** [comment]
@sturlath thank you for reporting this.  I'll look at this evening.

**Comment by kdawg1406** [comment]
@sturlath I didn't use the netstandard setting and it worked correctly.  Added the package, added the property, compiled.  No problem.

![image](https://cloud.githubusercontent.com/assets/5623887/17824487/508601ea-6630-11e6-9833-7f34894336f7.png)

When I tried to target the .NET Standard, I got this error.

![image](https://cloud.githubusercontent.com/assets/5623887/17824613/0ddfe936-6631-11e6-8a09-a9f3ce8f561c.png)

I spent 45 minutes trying to get the solution converted over to .NETStandard1.4 without any success.

I kept getting this error:  "Package restore failed. Rolling back package changes for 'App2'"

I strongly recommend staying away from netstandard until all nuget packages fully support it.

Best,

Karl

**Comment by kdawg1406** [comment]
@sturlath do you have a small repro I can downlaod?

**Comment by sturlath** [comment]
Hi I´m in Iceland so I´m few hours off so slow communication :-)

I had the same exact problem getting the netstandard to work but I managed in the end.

I created the repo for you to try out. 
https://github.com/sturlath/PowerToysDemo2 

The main thing with the netstandard stuff is that when you create a PCL you will have to 

1. Install .net Core https://www.microsoft.com/net/core#windows (lots of strange errors if you dont)
2. Unistall xamarin.forms from it and then change it to netstandard 
3. Add  "imports": "portable-monoandroid10+monotouch10+net45+win+win81+wp8+wpa81+xamarinios10" (profile 259) to project.json
4. Then re-install xamarin.forms


But yes... I might be to quick to try out new things... but it´s just to fun riding the wave of new things :-)

Hope this all helps.

**Comment by kdawg1406** [comment]
@sturlath I'll look at your repro.  At the moment, netstandard for Xamarin is an edge case or almost a not supported due to what you had to do just to set things up.

I'm thinking that the mono.dll used for refelction, does not work with netstandard assemblies.  I'll need to look at this.

**Comment by sturlath** [comment]
Ok thanks. Here is also a blog post with video  from James about using netstandard with xamarin.forms http://motzcod.es/post/148657853472/installing-a-pcl-into-netstandard-libraries

**Comment by kdawg1406** [comment]
@sturlath thank you.  I read the post and did a thread with James a while back.  His guidance to me was that it's very new.

IMHO: It will be awhile before wide-spread adoption.

**Comment by sturlath** [comment]
[Netstandard is project support coming soon](http://weeklyxamarin.com/issues/110#start)  see on [GitHub](https://github.com/mono/monodevelop/pull/1622?utm_campaign=Weekly%2BXamarin&utm_medium=web&utm_source=Weekly_Xamarin_110)

I think it (.net Core/netstandard) will be adopted very fast especially when the new  VS15 comes out.

**Comment by kdawg1406** [comment]
@sturlath When Xamarin provides a template that supports netstandard, I'll ensure XAML Power Toys works.  

FYI:  I create a netstandard project that was not Xamarin and it worked fine.  I also contacted the developer of Cecil Mono, he can't see any reason why it wouldn't work.  I'm confident it was a Xamarin or referenced assembly issue.

**Comment by kdawg1406** [comment]
@sturlath I just found out that the ObservableRangeCollection is included in a NuGet package that James M wrote.  This was the source of the error.
