### ISSUE TITLE
It sees only public classes

### ISSUE THREAD

**Issue by DJDoena** [Oceanware/XAMLPowerToys2015#3]
### Installed product versions
- Visual Studio: 2015 Professional
- This extension: 1.1.21 (probably, there is no "About" button in the app

I'm a conservative programmer. My code always has the least visibility unless otherwise needed. So the default state of any of my classes is "internal sealed" unless it's a nested class then it's even "private sealed".

But your Tool does not detect internal classes as possible ViewModels. Only public classes are detected.

**Comment by kdawg1406** [comment]
@DJDoena I'm on the road Saturday will look into this Sunday evening.

Thank you,

Karl

**Comment by kdawg1406** [comment]
@DJDoena apologies, I ran out of time Sunday.  I have time on Wednesday evening to work on this.

Karl

**Comment by kdawg1406** [comment]
@DJDoena are you asking for XAML Power Toys to show internal types in the assembly the view is located in or are you asking for a feature where XAML Power Toys has to build up a graph of your assemblies and take into account InternalsVisibleTo attribute or VB.NET friend assemblies?  

The second one would be much more work.

What is your exact request and scenario?  

Thank you,

Karl

**Comment by DJDoena** [comment]
Only the former

**Comment by kdawg1406** [comment]
@DJDoena roger.

**Comment by kdawg1406** [comment]
@DJDoena please get the build from the CI Server here:  http://vsixgallery.com/extension/d01c1624-8838-4097-bf77-f52d73fc7a1f/

After you have tested your scenarios, please let me know and I'll push it to the Visual Studio Gallery.

Nice feature request, thank you.

Karl

**Comment by DJDoena** [comment]
It works. :)

**Comment by kdawg1406** [comment]
@DJDoena great.

**Comment by kdawg1406** [comment]
@DJDoena now live on VS Gallery.
