### ISSUE TITLE
Silverlight 5 Combobox Generation Issue

### ISSUE THREAD

**Issue by MaherJendoubi** [Oceanware/XAMLPowerToys2015#4]
### Installed product versions
- Visual Studio: 2015 Professional
- This extension: 1.3.20

### Description
When I did geneate UI, I get :

![image](https://cloud.githubusercontent.com/assets/1798510/18619943/c15bfc0e-7e08-11e6-950f-418944b782c6.png)

### Steps to recreate
1. I created a ViewModel with two properties Name and Country then I build the project
2. I put 2 columns
3. In the first column, I put Name as a TextBox
4. In the second column, I put Country as Combobox then I did Generate UI

### Current behavior
the Xaml syntax is not valid there is a missing property

Thank you

**Comment by kdawg1406** [comment]
@MaherJendoubi can you please send me a screen shot of XAML Power Toys layout. Thank you!!!!

**Comment by MaherJendoubi** [comment]
![image](https://cloud.githubusercontent.com/assets/1798510/18620072/9c30d848-7e0b-11e6-83c1-e8c7559a4c3a.png)

**Comment by kdawg1406** [comment]
@MaherJendoubi NICE.  I see the problem but not sure why.  I'll fix this in the morning.

Best,

Karl

**Comment by MaherJendoubi** [comment]
👍  👍  👍

**Comment by kdawg1406** [comment]
@MaherJendoubi no bug.  You must set the ItemsSource.  After setting the items source it will correctly set what property of the ComboBox is actually bound to the viewmodel property.

Best,

Karl

**Comment by kdawg1406** [comment]
@MaherJendoubi I didn't want to add form validation to XAML Power Toys.  I'll update the readme and blog post to indicate that developers need to set the items source for ComboBox and BindablePicker.

**Comment by MaherJendoubi** [comment]
I apologize that's my mistake. Great tool! Thanks Karl 👍

**Comment by kdawg1406** [comment]
@MaherJendoubi NO WORRIES.  I need to update the readme.  Test away!!!!!!!!!!!!!!!!!!!

**Comment by MaherJendoubi** [comment]
![image](https://cloud.githubusercontent.com/assets/1798510/18632800/90a3aa82-7e79-11e6-986b-bbef93c1bcbb.png)

**Comment by kdawg1406** [comment]
@MaherJendoubi I assume everything is working correctly.  Best to you, Karl
