### ISSUE TITLE
Many fields, with spaces and ??? locks up

### ISSUE THREAD

**Issue by pedropete11** [Oceanware/XAMLPowerToys2015#5]
### Installed product versions
- Visual Studio: [example 2015 Professional]
- This extension: [example 1.1.21]

### Description
When the class contains many properties, or maybe with spacing (yes, weird), or if last field is a string, it locks up when you double click the bold class name.

### Steps to recreate
1. Choose ViewModel that has an object with many properties
2. Next, and left column will show the object name, class, in bold
3. Double click to expand
4. Locks up and never comes back. Crashes Visual Studio.

### Current behavior
Lock and crash VS

### Expected behavior
Should show the expanded list of class properties

I'll try to narrow down to a working and not working class and will append file.

**Comment by kdawg1406** [comment]
@pedropete11 thank you very much for reporting a problem.

Can you please upload example files that cause the problem.  I have many view models with many properties and never have an issue.

Be advised I injured my back and am on bed rest.  It will be a week or two before I can post fixes.

Thanks again for reporting this,

Karl

**Comment by kdawg1406** [comment]
@pedropete11 what language are you using, C# or VB?  I don't think C# supports class or property names with spaces.  Again, thank you for sending me example classes that are causing you problems.

Karl

**Comment by kdawg1406** [comment]
@pedropete11 do you have any additional information or a repo of the problem you had?  Thanks, Karl

**Comment by kdawg1406** [comment]
Closing, no response.
