### ISSUE TITLE
Crash after selecting a model with loop

### ISSUE THREAD

**Issue by ruslanfedoseenko** [Oceanware/XAMLPowerToys2015#7]
### Installed product versions
- Visual Studio: 2015 Community
- This extension: 1.5.22

### Description
Impossible to use with hierarchical view models with loops.
I have a viewmodel with loop on some level.  
Like ItemVM => SubItemVM => SomeObjectVM => ItemVM

### Steps to recreate
1. Create such objects structure 
2. Try to generate UI for ItemEditorVM

### Current behavior
VS was crashed

### Expected behavior
Should work fine.

**Comment by kdawg1406** [comment]
Can you please create a GitHub repo with your viewmodel and associated model classes so I can debug your exact issue.

Thank you,

Karl

**Comment by kdawg1406** [comment]
Also, what project type are you using?  WPF, SL, Xamarin, etc.

**Comment by kdawg1406** [comment]
Closing issue, assume the reported problem is no longer an issue.
