### ISSUE TITLE
Xamarin Forms and MVVM framework (FreshMVVM) causes assembly resolution error

### ISSUE THREAD

**Issue by johnmbaughman** [Oceanware/XAMLPowerToys2015#8]
### Installed product versions
- Visual Studio: 2017 Enterprise 15.3.3
- This extension: 1.5.22

### Description
When using FreshMVVM (haven't tried other frameworks) I get "Failed to resolve assembly 'Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'" after selecting the view model then Next. 

### Steps to recreate
1. Add <a href="https://github.com/rid00z/FreshMvvm" target="_blank">FreshMVVM</a> to a Xamarin Forms project. 
2. Add a content page.
3. Add a view model and inherit <a href="https://github.com/rid00z/FreshMvvm/blob/master/src/FreshMvvm/FreshBasePageModel.cs" target="_blank">FreshBasePageModel</a>
4. Build, open XAMLPowerToys as normal and select the view model, then click next.

### Current behavior
Get error as described, but when I only implement INotifyPropertyChanged and don't use FreshBasePageModel (which does also implements INotifyPropertyChanged), everything works.

### Expected behavior
Work just as if INotifyPropertyChange has been implemented directly.

**Comment by johnmbaughman** [comment]
Loving this tool and would like to have it demoed and implemented at work when we use it with FreshMVVM. Since Xamarin isn't showing any timeframe for having a designer, this is the best option (and that's putting it mildly!)

The learning curve to start using it is really short; it only took me about 10 minutes to figure it out!

Thank you for a great tool!

**Comment by johnmbaughman** [comment]
My workaround for now is to implement INotifyPropertyChanged, make my form, comment out the INotifyPropertyChanged implementation, and then implement FreshBasePageModel.

**Comment by kdawg1406** [comment]
@johnmbaughman I'll look at this issue this weekend. Nice bug report, easy to understand.  Thank you, Karl

**Comment by kdawg1406** [comment]
@johnmbaughman I cannot repro your issue.  Please open the attached project in VS 2017, restore NuGet packages and open XamPowerToys.  Works as advertised.

[App1.zip](https://github.com/Oceanware/XAMLPowerToys2015/files/1289930/App1.zip)

**Comment by johnmbaughman** [comment]
Hmmm... I still get it. I'll dig a little deeper and see what VS logs might say. This could definitely not be this app... I'd hate to have to reinstall VS, worse yet, Windows, to fix this. But we do what we have to do. I'll try out the enhancement shortly though.

Thanks!

**Comment by kdawg1406** [comment]
Did you try the project I attached?

Is your VS 2017 install completely updates?

You can try and clean your extensions cache. Download and install the Clear Cache extension from the Marketolace and run it. 

Let me know,

Karl

**Comment by johnmbaughman** [comment]
Yes, I used your project, especially since it's "cleaner" than mine. 

I'm pretty anal retentive about my updates... almost non-productively so.

I deleted the entire folder, repaired VS, and let create all the cache folders/files.

Still the same thing. 

If you have any other ideas, I'd definitely love to hear them, but I do have a workaround and I'm going to try creating the project as a non-PCL (.NET Standard) type and see what happens.

**Comment by kdawg1406** [comment]
Not sure what else to try. At this point I would pave the computer, fresh install.  Maybe wait until Microsoft releases VS15.4 then pave. 

Sometimes Xamarin tooling can be frustrating. 

Best to you,

Karl

**Comment by johnmbaughman** [comment]
Thanks for taking the time to look into this, it is much appreciated. I'll just start rebuilding this Windows installation and go piece by piece and see if I can get it to work. Sucks, but sometimes it just has be done. 

I pop back on here just for posterity to give a status once I get everything reinstalled. 

Thanks again,

-John

**Comment by kdawg1406** [comment]
@johnmbaughman be sure you read and follow this blog post:  [Setting Up Xamarin Dev on Windows](http://motzcod.es/post/157589380047/xamarin-cycle-9-preparing-machines)

**Comment by johnmbaughman** [comment]
Well, that was an exercise in futility. 

Read that post link, but it applies to VS 2015. I can compile an Android app (needs Java) and run it in the emulator, but bringing up XAML Power Toys results in that same error after a complete pave and rebuild from the OS up and installing ONLY VS 2017 15.3.3. 

I would love to figure out a log I can enable to see what is happening, but haven't a clue. Maybe tomorrow night, I'll run the extension in debug mode and see what I'm getting out of that.

For now, I'll just use my workaround and go from there.  It's still a great tool to get stuff done!

**Comment by kdawg1406** [comment]
@johnmbaughman why not download the source and run it.  It runs in the experimental instance of VS.

If you want to do this, we can Skype and I'll get you going in a jiff.

Karl

**Comment by johnmbaughman** [comment]
That's what I figured I'd do. I found a [Hello world tutorial to get it up and running](https://www.visualstudio.com/en-us/docs/integrate/ide/extensions/hello_world) so I should be ok to step through it. I'll just need to find the spot to set the break point to see what is happening at that point of failure.

**Comment by kdawg1406** [comment]
No need.  It will break on the exception. Location found.

**Comment by johnmbaughman** [comment]
Good point... 

-John

**Comment by johnmbaughman** [comment]
Here's the stack trace I got...

`   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Mono.Cecil.DefaultAssemblyResolver.Resolve(AssemblyNameReference name)
   at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
   at Mono.Cecil.TypeReference.Resolve()
   at XamlPowerToys.Reflection.TypeReflector.LoadPropertyInformation(TypeDefinition typeDefinition, ClassEntity classEntity, Hashtable assembliesToLoad, ProjectType projectFrameworkType, String parentPropertyName) in C:\Source\XAMLPowerToys2015\XamlPowerToys\Reflection\TypeReflector.cs:line 269
   at XamlPowerToys.Reflection.TypeReflector.SelectClassFromAllReferencedAssemblies(Project sourceProject, String xamlFileClassName, String sourceCommandName, ProjectType projectFrameworkType, String projectFrameworkVersion) in C:\Source\XAMLPowerToys2015\XamlPowerToys\Reflection\TypeReflector.cs:line 98
   at XamlPowerToys.Commands.DataFormGenerator.Generate() in C:\Source\XAMLPowerToys2015\XamlPowerToys\Commands\DataFormGenerator.cs:line 37`

And this is still using your sample app. I'm at a loss now, since I don't know anything about Mono.Cecil.

**Comment by johnmbaughman** [comment]
I'm going to try it on another computer so that I can compare installations. If I still see it, I may bring it up to the Mono.Cecil group to see what can be done.

**Comment by kdawg1406** [comment]
@johnmbaughman this is very strange.  Another computer is a great idea.

I can skype with you this weekend and try and help you sort this out for your system.

**Comment by johnmbaughman** [comment]
Same issue. I'm free on Sunday, if you are willing to give it a try. Thanks! If all projects like this had this type of customer support, the computing world would be a much better place!

**Comment by kdawg1406** [comment]
@johnmbaughman follow me on Twitter here:  [https://twitter.com/kdawg02](https://twitter.com/kdawg02)

And I can DM you my Skype and get yours.

Sunday is no problem.

What time zone are you in?

**Comment by johnmbaughman** [comment]
And I go back to having a Twitter account... ;) I haven't been on Twitter in almost 7 years. 

I'm mountain time zone.

John

**Comment by johnmbaughman** [comment]
Followed you: @RIPVmax

**Comment by kdawg1406** [comment]
Just followed you

**Comment by kdawg1406** [comment]
@johnmbaughman just sent you a skype contact request

**Comment by kdawg1406** [comment]
@johnmbaughman let's schedule the skype for Sunday.  You let me know what time is best for you.

Karl

**Comment by kdawg1406** [comment]
@johnmbaughman 

My Skype account is dead.  I sent you a skype contact from my skype for business account, please respond.
