### ISSUE TITLE
Enhancement: Add PageModel as a naming convention that is listed

### ISSUE THREAD

**Issue by johnmbaughman** [Oceanware/XAMLPowerToys2015#9]
### Installed product versions
- Visual Studio: 2017 
- This extension: 1.5.22

### Description
Add "PageModel" as a naming convention that the tool lists. 

### Current behavior
Only view/page models that end with "ViewModel" are listed. (Had to read the source to find this out... ;) 

### Expected behavior
Since Xamarin has a PageModel naming convention, it would be nice to be able to have those listed as well.

**Comment by kdawg1406** [comment]
@johnmbaughman sure, I can add this feature request this weekend.

**Comment by johnmbaughman** [comment]
Awesome!

**Comment by kdawg1406** [comment]
@johnmbaughman I've added this feature request.

See commit: [Feature Request Completed](https://github.com/Oceanware/XAMLPowerToys2015/commit/913c8c02f9d9156ff8204d8c1f30e99a6fbd061a
)

I just published the new version on the [CI server](http://vsixgallery.com/extension/d01c1624-8838-4097-bf77-f52d73fc7a1f/) and on the MarketPlace.  Should be live soon.

Thank you for the feature request,

Karl
